const data = {
  Products: [
    {
      id: 1,
      name: "Product 1",
      title: "Product 1 Title",
      slug: "product-1",
      price: 100,
      image: "https://source.unsplash.com/random/400x400",
      description: {
        short: "Short description",
        long: "Long description",
      },
      category: "category 1",
      rating: 4.5,
      numReviews: 10,
      numOrders: 10,
      numViews: 10,
      numFavorites: 10,
      numCart: 10,
      numWishlist: 10,
      numSold: 10,
      numInStock: 10,
    },
    {
      id: 2,
      name: "Product 2",
      title: "Product 2 Title",
      slug: "product-2",
      price: 200,
      image: "https://picsum.photos/200/300",
      description: {
        short: "Short description",
        long: "Long description",
      },
      category: "category 2",
      rating: 4.5,
      numReviews: 10,
      numOrders: 10,
      numViews: 10,
      numFavorites: 10,
      numCart: 10,
      numWishlist: 10,
      numSold: 10,
      numInStock: 10,
    },
    {
      id: 3,
      name: "Product 3",
      title: "Product 3 Title",
      slug: "product-3",
      price: 300,
      image: "https://picsum.photos/200/300",
      description: {
        short: "Short description",
        long: "Long description",
      },
      category: "category 3",
      rating: 4.5,
      numReviews: 10,
      numOrders: 10,
      numViews: 10,
      numFavorites: 10,
      numCart: 10,
      numWishlist: 10,
      numSold: 10,
      numInStock: 10,
    },
    {
      id: 4,
      name: "Product 4",
      title: "Product 4 Title",
      slug: "product-4",
      price: 400,
      image: "https://picsum.photos/200/300",
      description: {
        short: "Short description",
        long: "Long description",
      },
      category: "category 4",
      rating: 4.5,
      numReviews: 10,
      numOrders: 10,
      numViews: 10,
      numFavorites: 10,
      numCart: 10,
      numWishlist: 10,
      numSold: 10,
      numInStock: 10,
    },
    {
      id: 5,
      name: "Product 5",
      title: "Product 5 Title",
      slug: "product-5",
      price: 500,
      image: "https://picsum.photos/200/300",
      description: {
        short: "Short description",
        long: "Long description",
      },
      category: "category 5",
      rating: 4.5,
      numReviews: 10,
      numOrders: 10,
      numViews: 10,
      numFavorites: 10,
      numCart: 10,
      numWishlist: 10,
      numSold: 10,
      numInStock: 10,
    },
  ],
  users: [
    {
      id: 1,
      name: "User 1",
      email: "diwasdhungana@gmail.com",
      password: "123456",
    },
  ],
  orders: [
    {
      id: 1,
      user_id: 1,
      products: [
        {
          id: 1,
          quantity: 2,
        },
        {
          id: 2,
          quantity: 1,
        },
      ],
    },
    {
      id: 2,
      user_id: 2,
      products: [
        {
          id: 1,
          quantity: 1,
        },
        {
          id: 2,
          quantity: 2,
        },
      ],
    },
  ],
};
export default data;
